export const tableName = "api::municipio.municipio";

export const data = [
  {
    nodo: "CENTRO",
    nombre_municipio: "CHACHAGUI",
    codigo: "52240",
    label: "CHACHAGUI (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "CONSACA",
    codigo: "52207",
    label: "CONSACA (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "EL PEÑOL",
    codigo: "52254",
    label: "EL PEÑOL (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "EL TAMBO",
    codigo: "52260",
    label: "EL TAMBO (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "LA FLORIDA",
    codigo: "52381",
    label: "LA FLORIDA (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "PASTO",
    codigo: "52001",
    label: "PASTO (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "NARIÑO",
    codigo: "52480",
    label: "NARIÑO (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "TANGUA",
    codigo: "52788",
    label: "TANGUA (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "YACUANQUER",
    codigo: "52885",
    label: "YACUANQUER (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "SANDONÁ",
    codigo: "52683",
    label: "SANDONÁ (CENTRO)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "ANCUYA",
    codigo: "52036",
    label: "ANCUYA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "GUAITARILLA",
    codigo: "52320",
    label: "GUAITARILLA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "LINARES",
    codigo: "52411",
    label: "LINARES (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "LOS ANDES",
    codigo: "52418",
    label: "LOS ANDES (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "MALLAMA",
    codigo: "52435",
    label: "MALLAMA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "OSPINA",
    codigo: "52506",
    label: "OSPINA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "PROVIDENCIA",
    codigo: "52565",
    label: "PROVIDENCIA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "RICAURTE",
    codigo: "52612",
    label: "RICAURTE (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "SAMANIEGO",
    codigo: "52678",
    label: "SAMANIEGO (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "LA LLANADA",
    codigo: "52385",
    label: "LA LLANADA (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "SANTA CRUZ",
    codigo: "52699",
    label: "SANTA CRUZ (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "SAPUYES",
    codigo: "52720",
    label: "SAPUYES (CENTRO OCCIDENTE)",
  },
  {
    nodo: "CENTRO OCCIDENTE",
    nombre_municipio: "TUQUERRES",
    codigo: "52838",
    label: "TUQUERRES (CENTRO OCCIDENTE)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "EL CHARCO",
    codigo: "52250",
    label: "EL CHARCO (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "FRANCISCO PIZARRO",
    codigo: "52520",
    label: "FRANCISCO PIZARRO (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "LA TOLA",
    codigo: "52390",
    label: "LA TOLA (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "Magui",
    codigo: "52427",
    label: "Magui (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "MOSQUERA",
    codigo: "52473",
    label: "MOSQUERA (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "OLAYA HERRERA",
    codigo: "52490",
    label: "OLAYA HERRERA (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "ROBERTO PAYAN",
    codigo: "52621",
    label: "ROBERTO PAYAN (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "BARBACOAS",
    codigo: "52079",
    label: "BARBACOAS (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "SANTA BARBARA",
    codigo: "52696",
    label: "SANTA BARBARA (COSTA)",
  },
  {
    nodo: "COSTA",
    nombre_municipio: "TUMACO",
    codigo: "52835",
    label: "TUMACO (COSTA)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "EL ROSARIO",
    codigo: "52256",
    label: "EL ROSARIO (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "SAN LORENZO",
    codigo: "52687",
    label: "SAN LORENZO (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "POTOSÍ",
    codigo: "52560",
    label: "POTOSÍ (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "El Tablon de Gomez",
    codigo: "52258",
    label: "El Tablon de Gomez (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "SAN PABLO",
    codigo: "52693",
    label: "SAN PABLO (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "GUALMATAN",
    codigo: "52323",
    label: "GUALMATAN (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "ALBAN",
    codigo: "52019",
    label: "ALBAN (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CÓRDOBA",
    codigo: "52215",
    label: "CÓRDOBA (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "IPIALES",
    codigo: "52356",
    label: "IPIALES (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "LA CRUZ",
    codigo: "52378",
    label: "LA CRUZ (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "TAMINANGO",
    codigo: "52786",
    label: "TAMINANGO (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "GUACHUCAL",
    codigo: "52317",
    label: "GUACHUCAL (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "ARBOLEDA",
    codigo: "52051",
    label: "ARBOLEDA (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "LEIVA",
    codigo: "52405",
    label: "LEIVA (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CUASPUD",
    codigo: "52224",
    label: "CUASPUD (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "IMUES",
    codigo: "52354",
    label: "IMUES (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "BELEN",
    codigo: "52083",
    label: "BELEN (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "SAN BERNARDO",
    codigo: "52685",
    label: "SAN BERNARDO (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CUMBAL",
    codigo: "52227",
    label: "CUMBAL (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "BUESACO",
    codigo: "52110",
    label: "BUESACO (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "POLICARPA",
    codigo: "52540",
    label: "POLICARPA (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "PUERRES",
    codigo: "52573",
    label: "PUERRES (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "COLON",
    codigo: "52203",
    label: "COLON (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CONTADERO",
    codigo: "52210",
    label: "CONTADERO (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "ILES",
    codigo: "52352",
    label: "ILES (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "CUMBITARA",
    codigo: "52233",
    label: "CUMBITARA (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "ALDANA",
    codigo: "52022",
    label: "ALDANA (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "PUPIALES",
    codigo: "52585",
    label: "PUPIALES (SUR)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "LA UNION",
    codigo: "52399",
    label: "LA UNION (NORTE)",
  },
  {
    nodo: "NORTE",
    nombre_municipio: "SAN PEDRO DE CARTAGO",
    codigo: "52694",
    label: "SAN PEDRO DE CARTAGO (NORTE)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "FUNES",
    codigo: "52287",
    label: "FUNES (SUR)",
  },
];
