export const tableName = "api::municipio.municipio";

export const data = [
  {
    nodo: "CENTRO",
    nombre_municipio: "CHACHAGUI",
    codigo: "52240",
    label: "CHACHAGUI (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "LA FLORIDA",
    codigo: "52207",
    label: "LA FLORIDA (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "NARIÑO",
    codigo: "52254",
    label: "NARIÑO (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "PASTO",
    codigo: "52260",
    label: "PASTO (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "TANGUA",
    codigo: "52381",
    label: "TANGUA (CENTRO)",
  },
  {
    nodo: "CENTRO",
    nombre_municipio: "YACUANQUER",
    codigo: "52480",
    label: "YACUANQUER (CENTRO)",
  },
  {
    nodo: "GUAMBUYACO",
    nombre_municipio: "EL PEÑOL",
    codigo: "52001",
    label: "EL PEÑOL (GUAMBUYACO)",
  },
  {
    nodo: "GUAMBUYACO",
    nombre_municipio: "EL TAMBO",
    codigo: "52683",
    label: "EL TAMBO (GUAMBUYACO)",
  },
  {
    nodo: "GUAMBUYACO",
    nombre_municipio: "LA LLANADA",
    codigo: "52788",
    label: "LA LLANADA (GUAMBUYACO)",
  },
  {
    nodo: "GUAMBUYACO",
    nombre_municipio: "LOS ANDES SOTOMAYOR",
    codigo: "52885",
    label: "LOS ANDES SOTOMAYOR (GUAMBUYACO)",
  },
  {
    nodo: "JUANAMBU",
    nombre_municipio: "ARBOLEDA",
    codigo: "52036",
    label: "ARBOLEDA (JUANAMBU)",
  },
  {
    nodo: "JUANAMBU",
    nombre_municipio: "BUESACO",
    codigo: "52320",
    label: "BUESACO (JUANAMBU)",
  },
  {
    nodo: "JUANAMBU",
    nombre_municipio: "LA UNION",
    codigo: "52385",
    label: "LA UNION (JUANAMBU)",
  },
  {
    nodo: "JUANAMBU",
    nombre_municipio: "SAN LORENZO",
    codigo: "52411",
    label: "SAN LORENZO (JUANAMBU)",
  },
  {
    nodo: "JUANAMBU",
    nombre_municipio: "SAN PEDRO DE CARTAGO",
    codigo: "52418",
    label: "SAN PEDRO DE CARTAGO (JUANAMBU)",
  },
  {
    nodo: "LA CORDILLERA",
    nombre_municipio: "CUMBITARA",
    codigo: "52435",
    label: "CUMBITARA (LA CORDILLERA)",
  },
  {
    nodo: "LA CORDILLERA",
    nombre_municipio: "EL ROSARIO",
    codigo: "52506",
    label: "EL ROSARIO (LA CORDILLERA)",
  },
  {
    nodo: "LA CORDILLERA",
    nombre_municipio: "LEIVA",
    codigo: "52565",
    label: "LEIVA (LA CORDILLERA)",
  },
  {
    nodo: "LA CORDILLERA",
    nombre_municipio: "POLICARPA",
    codigo: "52612",
    label: "POLICARPA (LA CORDILLERA)",
  },
  {
    nodo: "LA CORDILLERA",
    nombre_municipio: "TAMINANGO",
    codigo: "52678",
    label: "TAMINANGO (LA CORDILLERA)",
  },
  {
    nodo: "LA SABANA",
    nombre_municipio: "GUAITARILLA",
    codigo: "52699",
    label: "GUAITARILLA (LA SABANA)",
  },
  {
    nodo: "LA SABANA",
    nombre_municipio: "OSPINA",
    codigo: "52720",
    label: "OSPINA (LA SABANA)",
  },
  {
    nodo: "LA SABANA",
    nombre_municipio: "SAPUYES",
    codigo: "52838",
    label: "SAPUYES (LA SABANA)",
  },
  {
    nodo: "LA SABANA",
    nombre_municipio: "TUQUERRES",
    codigo: "52079",
    label: "TUQUERRES (LA SABANA)",
  },
  {
    nodo: "LA SABANA",
    nombre_municipio: "IMUES",
    codigo: "52250",
    label: "IMUES (LA SABANA)",
  },
  {
    nodo: "LOS ABADES",
    nombre_municipio: "PROVIDENCIA",
    codigo: "52520",
    label: "PROVIDENCIA (LOS ABADES)",
  },
  {
    nodo: "LOS ABADES",
    nombre_municipio: "SAMANIEGO",
    codigo: "52390",
    label: "SAMANIEGO (LOS ABADES)",
  },
  {
    nodo: "LOS ABADES",
    nombre_municipio: "SANTACRUZ",
    codigo: "52427",
    label: "SANTACRUZ (LOS ABADES)",
  },
  {
    nodo: "OCCIDENTE",
    nombre_municipio: "CONSACA",
    codigo: "52473",
    label: "CONSACA (OCCIDENTE)",
  },
  {
    nodo: "OCCIDENTE",
    nombre_municipio: "SANDONA",
    codigo: "52490",
    label: "SANDONA (OCCIDENTE)",
  },
  {
    nodo: "OCCIDENTE",
    nombre_municipio: "ANCUYA",
    codigo: "52621",
    label: "ANCUYA (OCCIDENTE)",
  },
  {
    nodo: "OCCIDENTE",
    nombre_municipio: "LINARES",
    codigo: "52696",
    label: "LINARES (OCCIDENTE)",
  },
  {
    nodo: "PACIFICO SUR",
    nombre_municipio: "FRANCISCO PIZARRO",
    codigo: "52835",
    label: "FRANCISCO PIZARRO (PACIFICO SUR)",
  },
  {
    nodo: "PACIFICO SUR",
    nombre_municipio: "TUMACO",
    codigo: "52019",
    label: "TUMACO (PACIFICO SUR)",
  },
  {
    nodo: "PIE DE MONTE COSTERO",
    nombre_municipio: "MALLAMA",
    codigo: "52051",
    label: "MALLAMA (PIE DE MONTE COSTERO)",
  },
  {
    nodo: "PIE DE MONTE COSTERO",
    nombre_municipio: "RICAURTE",
    codigo: "52083",
    label: "RICAURTE (PIE DE MONTE COSTERO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "ALBAN",
    codigo: "52110",
    label: "ALBAN (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "BELEN",
    codigo: "52203",
    label: "BELEN (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "COLON",
    codigo: "52233",
    label: "COLON (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "EL TABLON DE GOMEZ",
    codigo: "52256",
    label: "EL TABLON DE GOMEZ (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "LA CRUZ",
    codigo: "52258",
    label: "LA CRUZ (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "SAN BERNARDO",
    codigo: "52378",
    label: "SAN BERNARDO (RIO MAYO)",
  },
  {
    nodo: "RIO MAYO",
    nombre_municipio: "SAN PABLO",
    codigo: "52399",
    label: "SAN PABLO (RIO MAYO)",
  },
  {
    nodo: "SANQUIANGA",
    nombre_municipio: "EL CHARCO",
    codigo: "52405",
    label: "EL CHARCO (SANQUIANGA)",
  },
  {
    nodo: "SANQUIANGA",
    nombre_municipio: "LA TOLA",
    codigo: "52540",
    label: "LA TOLA (SANQUIANGA)",
  },
  {
    nodo: "SANQUIANGA",
    nombre_municipio: "MOSQUERA",
    codigo: "52685",
    label: "MOSQUERA (SANQUIANGA)",
  },
  {
    nodo: "SANQUIANGA",
    nombre_municipio: "OLAYA HERRERA",
    codigo: "52687",
    label: "OLAYA HERRERA (SANQUIANGA)",
  },
  {
    nodo: "SANQUIANGA",
    nombre_municipio: "SANTA BARBARA",
    codigo: "52693",
    label: "SANTA BARBARA (SANQUIANGA)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "ALDANA",
    codigo: "52694",
    label: "ALDANA (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CONTADERO",
    codigo: "52786",
    label: "CONTADERO (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CORDOBA",
    codigo: "52022",
    label: "CORDOBA (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CUASPUD CARLOSAMA",
    codigo: "52210",
    label: "CUASPUD CARLOSAMA (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "CUMBAL",
    codigo: "52215",
    label: "CUMBAL (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "FUNES",
    codigo: "52224",
    label: "FUNES (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "GUACHUCAL",
    codigo: "52227",
    label: "GUACHUCAL (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "GUALMATAN",
    codigo: "52287",
    label: "GUALMATAN (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "ILES",
    codigo: "52317",
    label: "ILES (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "IPIALES",
    codigo: "52323",
    label: "IPIALES (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "POTOSI",
    codigo: "52352",
    label: "POTOSI (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "PUERRES",
    codigo: "52354",
    label: "PUERRES (SUR)",
  },
  {
    nodo: "SUR",
    nombre_municipio: "PUPIALES",
    codigo: "52356",
    label: "PUPIALES (SUR)",
  },
  {
    nodo: "TELEMBI",
    nombre_municipio: "BARBACOAS",
    codigo: "52560",
    label: "BARBACOAS (TELEMBI)",
  },
  {
    nodo: "TELEMBI",
    nombre_municipio: "MAGUI",
    codigo: "52573",
    label: "MAGUI (TELEMBI)",
  },
  {
    nodo: "TELEMBI",
    nombre_municipio: "ROBERTO PAYAN",
    codigo: "52585",
    label: "ROBERTO PAYAN (TELEMBI)",
  },
];
