export const tableName = "api::operador-pic.operador-pic";

export const data = [
  {
    nit: "814003182:9",
    operador_pic: "E.S.E. Centro Hospital Luis Antonio Montero Potosí - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "POTOSÍ",
  },
  {
    nit: "814003370:7",
    operador_pic: "E.S.E. Centro de Salud de Puerres",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PUERRES",
  },
  {
    nit: "891200528:8",
    operador_pic: "E.S.E. Hospital Departamental de Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PASTO",
  },
  {
    nit: "800084362:3",
    operador_pic: "E.S.E. Hospital Civil Regional - Ipiales",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "IPIALES",
  },
  {
    nit: "891201410:2",
    operador_pic: "E.S.E. Hospital el Buen Samaritano - La Cruz",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA CRUZ",
  },
  {
    nit: "891200952:8",
    operador_pic: "E.S.E. Hospital Eduardo Santos - La Unión",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA UNION",
  },
  {
    nit: "891200622:2",
    operador_pic: "E.S.E. Hospital Lorencita Villegas - Samaniego",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAMANIEGO",
  },
  {
    nit: "891200248:0",
    operador_pic: "E.S.E. Hospital Clarita Santos - Sandoná",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SANDONÁ",
  },
  {
    nit: "891200543:9",
    operador_pic: "E.S.E. Hospital San Carlos - San Pablo",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAN PABLO",
  },
  {
    nit: "800179870:2",
    operador_pic: "E.S.E. Hospital San Andrés - Tumaco",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "TUMACO",
  },
  {
    nit: "900000410:1",
    operador_pic: "E.S.E. Centro de Salud de Ancuyá - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ANCUYA",
  },
  {
    nit: "814006732:3",
    operador_pic: "E.S.E. Centro de Salud - Consacá",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CONSACA",
  },
  {
    nit: "814006908:2",
    operador_pic: "E.S.E. Centro de Salud San Bartolomé de Córdoba - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CÓRDOBA",
  },
  {
    nit: "814006607:8",
    operador_pic: "E.S.E. Centro de Salud de Cuaspud Carlosama",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CUASPUD",
  },
  {
    nit: "814001329:5",
    operador_pic: "E.S.E. Hospital - Cumbal",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CUMBAL",
  },
  {
    nit: "837000286:6",
    operador_pic: "E.S.E. Hospital - Guachucal",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "GUACHUCAL",
  },
  {
    nit: "814002021:7",
    operador_pic: "E.S.E. Centro Hospital Guaitarilla",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "GUAITARILLA",
  },
  {
    nit: "814006632:5",
    operador_pic: "E.S.E. Centro de Salud de Iles",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ILES",
  },
  {
    nit: "814006689:4",
    operador_pic: "E.S.E. Centro de Salud Nivel I Luis Acosta - La Unión",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA UNION",
  },
  {
    nit: "814006620:7",
    operador_pic: "E.S.E. Centro de Salud de Linares - Jorge Zambrano",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LINARES",
  },
  {
    nit: "814006625:3",
    operador_pic: "E.S.E. Centro de Salud Santiago de Mallama",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "MALLAMA",
  },
  {
    nit: "814007194:5",
    operador_pic: "E.S.E. Centro de Salud de Providencia - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PROVIDENCIA",
  },
  {
    nit: "814006654:7",
    operador_pic:
      "E.S.E Centro de Salud San Juan Bautista de Pupiales - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PUPIALES",
  },
  {
    nit: "900014225:6",
    operador_pic: "E.S.E. Centro de Salud de Sapuyes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAPUYES",
  },
  {
    nit: "840001036:7",
    operador_pic: "E.S.E. Centro Hospital Divino Niño - Tumaco",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "TUMACO",
  },
  {
    nit: "900091143:9",
    operador_pic: "E.S.E. Pasto Salud",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PASTO",
  },
  {
    nit: "900108282:0",
    operador_pic: "E.S.E. Centro de Salud de Yacuanquer",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "YACUANQUER",
  },
  {
    nit: "900122524:6",
    operador_pic: "E.S.E. Centro de Salud Municipal de Cartago",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAN PEDRO DE CARTAGO",
  },
  {
    nit: "814001677:3",
    operador_pic: "E.S.E. Centro de Salud Belén - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "BELEN",
  },
  {
    nit: "900131684:4",
    operador_pic: "E.S.E. Centro de Salud San José de Albán",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ALBAN",
  },
  {
    nit: "814001594:0",
    operador_pic: "E.S.E. Centro de Salud Señor de los Milagros",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "GUALMATAN",
  },
  {
    nit: "900126794:6",
    operador_pic:
      "E.S.E. Centro de Salud Sagrado Corazón de Jesús - El Contadero",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CONTADERO",
  },
  {
    nit: "900126464:0",
    operador_pic: "E.S.E. Centro de Salud San Isidro - El Peñol Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "EL PEÑOL",
  },
  {
    nit: "900127211:9",
    operador_pic: "E.S.E. Centro Hospital San Juan Bautista - Taminango",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "TAMINANGO",
  },
  {
    nit: "900127207:9",
    operador_pic: "E.S.E. Centro de Salud San Sebastian - Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "NARIÑO",
  },
  {
    nit: "900121152:5",
    operador_pic: "E.S.E. Hospital Ricaurte",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "RICAURTE",
  },
  {
    nit: "900134576:0",
    operador_pic: "E.S.E. Centro de Salud San Bernardo",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAN BERNARDO",
  },
  {
    nit: "900126676:5",
    operador_pic: "E.S.E. Centro de Salud San Miguel Arcángel - Ospina",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "OSPINA",
  },
  {
    nit: "900125582:7",
    operador_pic: "E.S.E. Tangua Salud Hermes Andrade Mejía",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "TANGUA",
  },
  {
    nit: "900140894:2",
    operador_pic: "E.S.E. Centro de Salud Señor del Mar",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "FRANCISCO PIZARRO",
  },
  {
    nit: "900127853:7",
    operador_pic: "E.S.E. Centro de Salud Camilo Hurtado Cifuentes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "OLAYA HERRERA",
  },
  {
    nit: "900153346:4",
    operador_pic: "E.S.E. Centro Hospital San Luis - El Tambo",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "EL TAMBO",
  },
  {
    nit: "900136920:0",
    operador_pic: "E.S.E. Centro de Salud La Buena Esperanza - Colón",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "COLON",
  },
  {
    nit: "900134497:7",
    operador_pic: "E.S.E. Centro de Salud Nuestra Señora de Fátima - Chachagüí",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CHACHAGUI",
  },
  {
    nit: "900142446:5",
    operador_pic: "E.S.E. Centro de Salud de Los Andes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LOS ANDES",
  },
  {
    nit: "900109862:7",
    operador_pic: "E.S.E. Centro de Salud Santa Bárbara - Iscuandé",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SANTA BARBARA",
  },
  {
    nit: "900176479:4",
    operador_pic: "E.S.E. Centro de Salud Policarpa",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "POLICARPA",
  },
  {
    nit: "900128655:1",
    operador_pic: "E.S.E. Centro de Salud Funes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "FUNES",
  },
  {
    nit: "900142999:6",
    operador_pic: "E.S.E. Santiago Apóstol - Imués",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "IMUES",
  },
  {
    nit: "900135676:3",
    operador_pic: "E.S.E. Centro de Salud San Miguel - Arboleda",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ARBOLEDA",
  },
  {
    nit: "900145604:6",
    operador_pic: "E.S.E. Centro de Salud El Rosario",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "EL ROSARIO",
  },
  {
    nit: "900154361:1",
    operador_pic: "E.S.E. Centro de Salud de Tablón de Gómez",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "El Tablon de Gomez",
  },
  {
    nit: "900140292:9",
    operador_pic: "E.S.E. Centro de Salud San Juan Bosco - La Llanada",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA LLANADA",
  },
  {
    nit: "900167616:9",
    operador_pic: "E.S.E. Centro de Salud San Francisco",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "MOSQUERA",
  },
  {
    nit: "900190473:9",
    operador_pic: "E.S.E. Municipal de Ipiales",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "IPIALES",
  },
  {
    nit: "900129891:6",
    operador_pic: "E.S.E. Centro de Salud de Guachavés",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SANTA CRUZ",
  },
  {
    nit: "900192544:2",
    operador_pic: "E.S.E. Centro Hospital de La Florida",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA FLORIDA",
  },
  {
    nit: "900192678:0",
    operador_pic: "E.S.E. Centro de Salud Nuestra Señora del Pilar",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ALDANA",
  },
  {
    nit: "900160887:6",
    operador_pic: "E.S.E. Centro Hospital Las Mercedes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "ROBERTO PAYAN",
  },
  {
    nit: "900192832:9",
    operador_pic: "E.S.E. Centro de Salud San Lorenzo",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SAN LORENZO",
  },
  {
    nit: "900113729:0",
    operador_pic: "E.S.E. Centro de Salud Saul Quiñones",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "Magui",
  },
  {
    nit: "900166361:1",
    operador_pic: "E.S.E. Centro de Salud Nuestra Señora del Carmen - La Tola",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LA TOLA",
  },
  {
    nit: "900179095:3",
    operador_pic: "E.S.E. San Pedro de Cumbitara",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "CUMBITARA",
  },
  {
    nit: "900193766:5",
    operador_pic: "E.S.E. Centro de Salud San José de Leiva",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "LEIVA",
  },
  {
    nit: "900142579:6",
    operador_pic: "E.S.E. Centro de Salud Virgen de Lourdes",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "BUESACO",
  },
  {
    nit: "891200638:1",
    operador_pic: "E.S.E. CEHANI ",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PASTO",
  },
  {
    nit: "900408019:7",
    operador_pic: "IPS - Indígena del Pueblo Inga en Aponte",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "El Tablon de Gomez",
  },
  {
    nit: "900056747:9",
    operador_pic: "IPS - Indígena Guaitara",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "IPIALES",
  },
  {
    nit: "814005761:2",
    operador_pic: "IPS - Indígena Mingasalud Resguardo de Guachavés",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SANTA CRUZ",
  },
  {
    nit: "800118954:1",
    operador_pic: "Universidad de Nariño",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "PASTO",
  },
  {
    nit: null,
    operador_pic: "Fundación",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SIN ESPECIFICAR",
  },
  {
    nit: null,
    operador_pic: "Otro",
    departamento: "DEPARTAMENTO DE NARIÑO",
    municipio: "SIN ESPECIFICAR",
  },
];
